version: "3"
services:
  api:
    build: .
    container_name: api
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app 
    ports:
      - "8000:8000"
    depends_on:
      - db
  cache:
    image: redis:latest
    container_name: cache
    restart: always  
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data:
  redis_data:
    